cc_binary(
    name = "main",
    srcs = ["starter.cc", "common.h"],
    deps = [
       "//console:console",
       "//graphics:graphics",
       "@tiger//session:session",
       "@gnu//gnu:profile",
    ],
    linkstatic = 0
)