config_setting(
    name = "windows",
    define_values = {
        "platform" : "windows",
    },
    visibility = ["//visibility:public"],
)

# bazel build //main:main --define platform=windows
# bazel build //main:main --define platform=linux
config_setting(
    name = "linux",
    define_values = {
        "platform" : "linux",
    },
    visibility = ["//visibility:public"],
)
