workspace(name = "lion")

# local bazel deps
local_repository(
    name = "tiger",
    path = "../tiger",
)

# local non-bazel deps
new_local_repository(
    name = "duck",
    path = "../duck",
    build_file = "duck.BUILD",
)

# remote bazel deps
git_repository(
    name = "gnu",
    remote = "https://github.com/Sunhick/bazel101-libs.git",
    tag = "v1.0.1",
)

new_http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
    sha256 = "b58cb7547a28b2c718d1e38aee18a3659c9e3ff52440297e965f5edffe34b6d0",
    build_file = "gtest.BUILD",
    strip_prefix = "googletest-release-1.7.0",
)
